version: "3.9"
services:
  nextforumv2:
    container_name: nextforumv2
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:test@postgres:5432/nextforumv2_testdb?schema=public
      - ENV=test
    restart: always
    command: sh -c "pnpm exec prisma migrate reset --force && pnpm dev"
  postgres:
    container_name: postgres
    image: "postgres:14-alpine"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=nextforumv2_testdb
    ports:
      - "5432:5432"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
